name: java-project

on:
  push:
    branches:
      - Master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Cloning Java Project
        uses: actions/checkout@v4

      - name: Install Java
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Check Java Version
        run: java --version
