name: java-project
on:
  push:
    branches: ['Master']

jobs:
  build:
     runs-on: ubuntu-latest

     steps:
       - name: cloning java project
         uses: actions/checkout@v7.0.0

        - name: install  java
          uses:  actions/setup-java@v5.5.0
          with: 
            java-version: '21'
            distribution: "temurin"

        - name: Generating package for maven project
          run: java --version 
