name: java-CI/CD
on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout gitub repo
        uses: actions/checkout@v7.0.0
  
      - name: install java
        uses: actions/setup-java@v5.5.0
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: compile java
        run: javac Test.java

      - name: run java program
        run: java Test
