name: java-app
on: 
  workflow_dispatch: 

jobs:
  build:
    strategy:
      matrix:
        environment: ["beta","gamma","delta"]
        version: [17,21]
        os: ["ubuntu-latest","windows-latest"]
    runs-on: ${{ matrix.os }}

    steps:
      - name: cloning
        uses: actions/checkout@v7.0.0

      - name: install
        uses: actions/setup-java@v5.5.0
        with:
          java-version: ${{ matrix.os }}
          distribution: 'temurin'

      - name: compile
        run: javac Test.java

      - name: environment
        run: echo "${{ matrix.environment }} "

      - name: execute java project
        run: java Test

      - name: java version
        run: java --version
      
